// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonProfileAPI.Data;

#nullable disable

namespace PersonProfileAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406081851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonProfileAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 500000m,
                            Floor = "3rd Floor",
                            ManagerName = "Sarah Chen",
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 300000m,
                            Floor = "2nd Floor",
                            ManagerName = "Mike Thompson",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Budget = 200000m,
                            Floor = "1st Floor",
                            ManagerName = "Lisa Park",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 4,
                            Budget = 350000m,
                            Floor = "4th Floor",
                            ManagerName = "James Rodriguez",
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 5,
                            Budget = 400000m,
                            Floor = "2nd Floor",
                            ManagerName = "Amy Watson",
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("PersonProfileAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            City = "New York",
                            DateJoined = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Smith",
                            Salary = 95000m
                        },
                        new
                        {
                            Id = 2,
                            Age = 45,
                            City = "Chicago",
                            DateJoined = new DateTime(2018, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Johnson",
                            Salary = 72000m
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            City = "New York",
                            DateJoined = new DateTime(2019, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Email = "charlie@example.com",
                            FirstName = "Charlie",
                            IsActive = true,
                            LastName = "Williams",
                            Salary = 105000m
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            City = "Houston",
                            DateJoined = new DateTime(2021, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Email = "diana@example.com",
                            FirstName = "Diana",
                            IsActive = false,
                            LastName = "Brown",
                            Salary = 68000m
                        },
                        new
                        {
                            Id = 5,
                            Age = 40,
                            City = "Chicago",
                            DateJoined = new DateTime(2017, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Email = "eve@example.com",
                            FirstName = "Eve",
                            IsActive = true,
                            LastName = "Jones",
                            Salary = 110000m
                        },
                        new
                        {
                            Id = 6,
                            Age = 25,
                            City = "Phoenix",
                            DateJoined = new DateTime(2022, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Email = "frank@example.com",
                            FirstName = "Frank",
                            IsActive = true,
                            LastName = "Garcia",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 7,
                            Age = 33,
                            City = "New York",
                            DateJoined = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "HR",
                            Email = "grace@example.com",
                            FirstName = "Grace",
                            IsActive = true,
                            LastName = "Miller",
                            Salary = 78000m
                        },
                        new
                        {
                            Id = 8,
                            Age = 50,
                            City = "Houston",
                            DateJoined = new DateTime(2015, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Email = "hank@example.com",
                            FirstName = "Hank",
                            IsActive = false,
                            LastName = "Davis",
                            Salary = 88000m
                        },
                        new
                        {
                            Id = 9,
                            Age = 38,
                            City = "Phoenix",
                            DateJoined = new DateTime(2019, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Email = "ivy@example.com",
                            FirstName = "Ivy",
                            IsActive = true,
                            LastName = "Rodriguez",
                            Salary = 92000m
                        },
                        new
                        {
                            Id = 10,
                            Age = 42,
                            City = "Chicago",
                            DateJoined = new DateTime(2016, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Email = "jack@example.com",
                            FirstName = "Jack",
                            IsActive = true,
                            LastName = "Wilson",
                            Salary = 85000m
                        },
                        new
                        {
                            Id = 11,
                            Age = 29,
                            City = "New York",
                            DateJoined = new DateTime(2021, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Email = "karen@example.com",
                            FirstName = "Karen",
                            IsActive = true,
                            LastName = "Martinez",
                            Salary = 71000m
                        },
                        new
                        {
                            Id = 12,
                            Age = 36,
                            City = "Houston",
                            DateJoined = new DateTime(2018, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Email = "leo@example.com",
                            FirstName = "Leo",
                            IsActive = true,
                            LastName = "Anderson",
                            Salary = 99000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
